import type { Metadata } from "next";
import { Urbanist,Figtree } from "next/font/google";
import "./globals.css";

//! google custom font
const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
  style: ["normal"],
  preload: true,
});
const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
  style: ["normal"],
  preload: true,
});


export const metadata: Metadata = {
  title: "Fametonic: The Smart Way to Go Viral on Social Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${figtree.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
